### ISSUE TITLE
The matrix in sparse_csr.npz file is not valid because we compressed target values together with features

### ISSUE THREAD

**Issue by tiavlovskiegor24** [katyaputintseva/ubird#23]
I will fix the code in (Sparse to .csr.ipynb) and upload the valid sparse_csr.npz

**Comment by tiavlovskiegor24** [comment]
https://github.com/katyaputintseva/ubird/blob/Egor/Creating%20and%20saving%20sparse%20feature%20matrix%20and%20target%20values%20to%20file.ipynb

Here is the code for creating out sparse feature matrix and storing it in a file.

**Comment by tiavlovskiegor24** [comment]
Now our data will be stored in sparse_csr.npz, target_values.npz files for final processing and running learning algorithms on it

**Comment by XiaoxiaLin** [comment]
Hi, .npz is a zip file, but in order to export data to mlab, I think we need JSON, CSV or TSV file. Not sure how to do it... Anyone can also have a look into it please?

Are they actually 4 arrays, or files?  
<class 'numpy.lib.npyio.NpzFile'>
['indices', 'indptr', 'shape', 'data'] 
[   0 1879 1880 ..., 1878 1879 1880] 
[     0      3     10 ..., 320425 320430 320437] 
[54024  1882] 
[1 1 1 ..., 1 1 1]  

Thanks,

**Comment by tiavlovskiegor24** [comment]
Alright so now I create and store our matrix and target values in csv format.

Here is the annotated ipython notebook for constructing sparse matrix from raw data:

https://github.com/katyaputintseva/ubird/blob/Egor/Creating%20and%20saving%20sparse%20feature%20matrix%20and%20target%20values%20to%20file.ipynb

There are 5 csv files overall:
target_values - brightness values and their std 
col_names - mutation names corresponding to our columns
indices - matrix column indices locations where entries are non-zero.
indptr -  ranges for each row in indices
shape - shape of our sparse matrix

I am not storing data array for our matrix because our entries are all "1".

In this file is the python codes for writing and reading our sparse matrix to and from csv files:
https://github.com/katyaputintseva/ubird/blob/Egor/write_read_sparse_csr.py
