### ISSUE TITLE
Implement the method for exporting mutation weights from Tensorflow 

### ISSUE THREAD

**Issue by BielStela** [katyaputintseva/ubird#25]
Testing criteria: implement the code into the existing python script and let someone else run it

**Comment by tiavlovskiegor24** [comment]
Suppose after training our model we want to see the effect of single mutation "SI186V" for example.

Instead of extracting weights for this particular feature(i.e. column) we can simply feed the model with a vector [0 0 0 0 0 0 ...0 1 0 ... 0 0 0 0 ] with all zeros except for location corresponding to our feature (i.e. mutation) "SI186V". Then our model will predict the brightness of a mutant protein with a single mutation "SI186V" right? We can compare its brightness with out base case and see if it is beneficial or not.

This is better because the bare weights are just some numbers which were generated by complex interplay between many features and we don't know what do they actually represent.

Does it make sense?
