### ISSUE TITLE
Implement the methods for extracting weights and model into the initial neural net structure

### ISSUE THREAD

**Issue by katyaputintseva** [katyaputintseva/ubird#28]
Examine the results obtained

**Comment by tiavlovskiegor24** [comment]
Suppose after training our model we want to see the effect of single mutation "SI186V" for example.

Instead of extracting weights for this particular feature(i.e. column) we can simply feed the model with a vector [0 0 0 0 0 0 ...0 1 0 ... 0 0 0 0 ]  with all zeros except for location corresponding to our feature (i.e. mutation) "SI186V". Then our model will predict the brightness of a mutant protein with a single mutation "SI186V" right? We can compare its brightness with out base case and see if it is beneficial or not.

This is better because the bare weights are just some numbers which were generated by complex  interplay between many features and we don't know what do they actually represent. 

Does it make sense?

**Comment by katyaputintseva** [comment]
@tiavlovskiegor24 Sorry missed your comment! It totally does, might be a better way of extracting the mutations of interest. Thanks!

The other thing I was thinking about is how to extract the level of confidence for those mutations. It must depend on the number of times this mutation is seen and the combinations it is seen within (meaning that if we saw this mutation in many combinations -- but all of those were super-multiple mutants, can we really trust the result?..). On the other hand, I think, the latter type of mutations will most probably fall into the negative category.
